refactor install scripts & other changes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,44 +2,42 @@
 
 cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
 
-echo "Ensuring repository is up to date..."
-git pull origin main
-echo
-
-if ! command -v brew >/dev/null 2>&1; then
-    echo "Unable to locate Homebrew, installing..."
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-fi
-if command -v brew >/dev/null 2>&1; then
-    brew bundle check || brew bundle install --no-lock
-    BREW_PREFIX=$(brew --prefix)
-    BREW_BIN="$BREW_PREFIX/bin"
-    echo
-
-    if ! grep -F -q "$BREW_BIN" /etc/paths; then
-        echo "configuring /etc/path for Homebrew"
-        echo "$BREW_BIN" | cat - /etc/paths | sudo tee /etc/paths
-        echo
-    fi
-
-    if ! grep -F -q "$BREW_BIN/fish" /etc/shells; then
-        echo "configuring default shell: $BREW_BIN/fish"
-        echo "$BREW_BIN/fish" | sudo tee -a /etc/shells
-        chsh -s "$BREW_BIN/fish"
-        echo
-    fi
-else
-    echo "ERROR: Homebrew is still not in your PATH, aborting installation."
-    exit 1
+if [[ -n $(command -v git) ]]; then
+  echo "Ensuring repository is up to date..."
+  git pull origin main
+  echo
 fi
 
-if ! command -v stow >/dev/null 2>&1; then
-    echo "ERROR: Unable to locate stow, aborting installation."
-    exit 1
+case $(uname -s) in
+"Darwin")
+  source install-macos || exit 1
+  ;;
+"Linux")
+  source install-linux || exit 1
+  ;;
+*)
+  echo "ERROR: Unsupported system, aborting installation." && exit 1
+  ;;
+esac
+
+if [[ -z $(command -v stow) ]]; then
+  echo "ERROR: Unable to locate stow, aborting installation."
+  exit 1
 fi
 
 stow -v editorconfig
 
+FISH_PATH=$(command -v fish)
+if ! grep -F -q "$FISH_PATH" /etc/shells; then
+  echo "configuring /etc/shells"
+  echo "$FISH_PATH" | sudo tee -a /etc/shells
+  echo
+fi
+if [[ "$SHELL" != "$FISH_PATH" ]]; then
+  echo "configuring default shell: $FISH_PATH"
+  chsh -s "$FISH_PATH"
+  echo
+fi
 mkdir -p "$HOME/.config/fish/completions" "$HOME/.config/fish/conf.d" "$HOME/.config/fish/functions"
 stow -v fish
 
@@ -50,16 +48,18 @@ stow -v login
 stow -v node
 stow -v psql
 
-mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh" && touch "$HOME/.ssh/config.personal"
+mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
+touch ssh/.ssh/config.personal
 stow -v ssh
 if [[ ! -e "$HOME/.ssh/id_ed25519" ]]; then
-    echo "generating ssh key"
-    ssh-keygen -t ed25519 -a 100 -C "$(whoami)@$(hostname)"
+  echo "generating ssh key"
+  ssh-keygen -t ed25519 -a 100 -C "$(whoami)@$(hostname)"
 fi
 if [[ ! -e "$HOME/.ssh/id_rsa" ]]; then
-    echo "generating ssh key (rsa)"
-    ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname)"
+  echo "generating ssh key (rsa)"
+  ssh-keygen -t rsa -b 4096 -a 100 -C "$(whoami)@$(hostname)"
 fi
+chmod 644 "$HOME/.ssh/"*.pub
 
 stow -v starship
 
